[project]
name = "xyplug-sun-trigger"
version = "1.0.1"
description = "xyOps trigger plugin to execute jobs depending on the sun"
requires-python = ">=3.9"
dependencies = [
    "requests"
]

[project.scripts]
xyplug-sun-trigger = "sun_trigger.main:main"

[tool.setuptools]
packages = ["sun_trigger"]
